### ISSUE TITLE
Including the mediator

### ISSUE THREAD

**Issue by ghost** [chaplinjs/chaplin-auth#10]
I'm looking at the SessionController in this example and I notice that it's including the mediator like `require 'mediator'`. Elsewhere in example Chaplin apps, it seems that the mediator always lives under `Chaplin.mediator`.

Could someone provide some clarification on how this is supposed to work?

**Comment by paulmillr** [comment]
`require 'mediator'` loads mediator.coffee module in the app root.

I usually did `module.exports = Chaplin.mediator` there.

So there’s no difference. You can use chaplin.mediator if you don’t have that module.

**Comment by ghost** [comment]
Ah, fantastic. Thank you.
