### ISSUE TITLE
The license is invalid

### ISSUE THREAD

**Issue by ghostbar** [chaplinjs/chaplin-auth#2]
For the license having validity you need to add actual legal-persons, being registered companies or people. I believe The Chaplin Contributors is not a legal-entity so this license is not valid.

There should be real-people or real-companies as Copyright owners.

We had this issue in pkg-perl team @ Debian and that's what SPI and FSF legal-team recommended us.

**Comment by paulmillr** [comment]
same with main chaplin repo

cc @molily
