### ISSUE TITLE
Provide more simple service provider

### ISSUE THREAD

**Issue by paulmillr** [chaplinjs/chaplin-auth#4]
https://github.com/paulmillr/brunch-with-chaplin/issues/42

**Comment by andriijas** [comment]
an example of username - password login should be provided by default.

Most apps provides their own username password service and then on top of that single click login via fb,twitter, google etc

**Comment by mehcode** [comment]
correct -- this chaplin-auth should massage the differences until every app has login via self, fb,twitter, google etc just by including this (of course pick and chose, for proxies, etc would exist). This is definitely on my list of contrib plugins to finalize first.

One of the main problems with providing self user / pass login is how it is done on the server. Backbone states your API must be RESTful so chaplin would follow the same so it stands to reason we can at least assume the communication is RESTful (basic-auth + session cookie, though servers do different things in this strain as well). We just need to be fairly configurable in the implementation of how we talk to the server.

**Comment by andriijas** [comment]
True but I think it should still be up to the implementer (me) to include services/myservice.coffee which does something with the username and password and somehow the loginview make a login attempt on that service.

**Comment by mehcode** [comment]
From an implementer's prospective I see this:

``` coffee
auth = require('chaplin-contrib-auth')  # Or something
Facebook = auth.services.Facebook  # Or some thing like requiring services/facebook
class LoginView extends auth.LoginView
  services: [
    auth.services.Facebook,
    auth.services.Self # Maybe a better name
    (credentials...) ->
      # Custom ?
      return someUserModel
  ]

  # By default there is a services subview that is a collection view 
  # or something and could be used to select the service 
  # All able to overridden nicely of course
```

That part I have no trouble visualizing. It is the part that communicates with the server for normal user / pass login would be tricky. Probably in here it'll be a stricly RESTful implementation using basic-auth and session cookies but it'll be able to derived from and made to do whatever to talk to the backend
