### ISSUE TITLE
app keys in client

### ISSUE THREAD

**Issue by andriijas** [chaplinjs/chaplin-auth#5]
isnt it bad idea to have app keys in client side code? Others can use them to designate them self as you.

**Comment by paulmillr** [comment]
yea, but what else can we do? source code can be quite obfuscated so you won’t be able to spot it in the first place.

**Comment by knuton** [comment]
Obfuscation would be disastrous.

@andriijas, this would be a problem in OAuth 1, but OAuth 2 has the concept of a user-agent flow that prevents the issue[1](http://tools.ietf.org/html/draft-ietf-oauth-v2-02#section-3.5.1) and is being used by the service providers in this example.
